format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

palette = "rose-pine-moon"

[palettes.rose-pine-moon]
overlay = '#393552'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ea9a97'
pine = '#3e8fb0'
foam = '#9ccfd8'
iris = '#c4a7e7'

[directory]
style = "pine"

[character]
success_symbol = "[❯](iris)"
error_symbol = "[❯](love)"
vimcmd_symbol = "[❮](foam)"

[git_branch]
format = "[$branch]($style)"
style = "foam"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](129) ($ahead_behind$stashed)]($style) "
style = "love"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "love"

[cmd_duration]
format = "[$duration]($style) "
style = "gold"

[username]
format = "[$user]($style) "
style_root = "love"
style_user = "iris"

[python]
format = "[$virtualenv]($style) "
style = "pine"
