FROM ubuntu:24.04

# hadolint ignore=DL3008
RUN apt-get update \
    && apt-get install --no-install-recommends -y \
    build-essential \
    ca-certificates \
    git \
    ninja-build \
    gettext \
    cmake \
    unzip \
    curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists

COPY build.sh /
COPY control.in /
